[
{"lib/symphony_elixir/agent_harness.ex", "The pattern can never match the type 
  {:error,
   atom()
   | {:missing_fields, [any(), ...]}
   | %{
       :__exception__ => true,
       :__struct__ => YamlElixir.FileNotFoundError | YamlElixir.ParsingError,
       :message => binary(),
       :column => _,
       :line => _,
       :type => _
     }}
."},
{"lib/symphony_elixir/agent_harness.ex", "The pattern can never match the type binary()."},
{"lib/symphony_elixir/behavioral_proof.ex", "Unknown type: SymphonyElixir.BehavioralProof.Result.t/0."},
{"lib/symphony_elixir/cli.ex", "The created anonymous function has no local return."},
{"lib/symphony_elixir/cli.ex", "The pattern can never match the type {:error, binary()}."},
{"lib/symphony_elixir/cli.ex", "The pattern can never match the type 
  {:error,
   atom()
   | %Jason.DecodeError{
       :__exception__ => true,
       :data => binary(),
       :position => integer(),
       :token => _
     }}
."},
{"lib/symphony_elixir/codex/app_server.ex", "The pattern variable __payload_string@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/codex/app_server.ex", "The pattern variable __command@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/config.ex", "Invalid type specification for function runner."},
{"lib/symphony_elixir/config.ex", "The guard clause can never succeed."},
{"lib/symphony_elixir/config.ex", "The pattern variable __section@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/config.ex", "The pattern variable __labels@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/coverage_audit.ex", "Function :cover.modules/0 does not exist."},
{"lib/symphony_elixir/coverage_audit.ex", "Function :cover.analyse/3 does not exist."},
{"lib/symphony_elixir/credential_registry.ex", "The function call default_allowance will not succeed."},
{"lib/symphony_elixir/credential_registry.ex", "Function default_allowance/3 has no local return."},
{"lib/symphony_elixir/credential_registry.ex", "The function call contractor_write_without_registry? will not succeed."},
{"lib/symphony_elixir/credential_registry.ex", "Function contractor_write_without_registry?/2 has no local return."},
{"lib/symphony_elixir/credential_registry.ex", "The function call contractor_mode? will not succeed."},
{"lib/symphony_elixir/delivery_engine.ex", "The guard clause can never succeed."},
{"lib/symphony_elixir/delivery_engine.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/delivery_engine.ex", "The pattern variable __issue@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/delivery_engine.ex", "Function risk_review_required?/4 has no local return."},
{"lib/symphony_elixir/delivery_engine.ex", "The function call contractor_mode? will not succeed."},
{"lib/symphony_elixir/issue_source.ex", "The function call create_comment will not succeed."},
{"lib/symphony_elixir/issue_source.ex", "The function call update_issue_state will not succeed."},
{"lib/symphony_elixir/issue_source.ex", "The function call attach_link will not succeed."},
{"lib/symphony_elixir/json_log_formatter.ex", "Unknown type: :logger.message/0."},
{"lib/symphony_elixir/json_log_formatter.ex", "Unknown type: :logger.time/0."},
{"lib/symphony_elixir/manual_issue_store.ex", "The pattern can never match the type 
  {:error,
   atom()
   | %Jason.DecodeError{
       :__exception__ => true,
       :data => binary(),
       :position => integer(),
       :token => _
     }}
."},
{"lib/symphony_elixir/manual_issue_store.ex", "The pattern variable __text@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/observability.ex", "The pattern can never match the type true."},
{"lib/symphony_elixir/orchestrator.ex", "Invalid type specification for function state_slots_available_for_test."},
{"lib/symphony_elixir/orchestrator.ex", "Invalid type specification for function running_issue_count_for_state_for_test."},
{"lib/symphony_elixir/orchestrator.ex", "Invalid type specification for function label_gate_status_for_test."},
{"lib/symphony_elixir/orchestrator.ex", "The guard clause can never succeed."},
{"lib/symphony_elixir/orchestrator.ex", "The pattern can never match the type 
  {:ok,
   [
     %SymphonyElixir.Linear.Issue{
       :assigned_to_worker => boolean(),
       :assignee_id => nil | binary(),
       :blocked_by => _,
       :branch_name => nil | binary(),
       :canonical_identifier => nil | binary(),
       :created_at =>
         nil
         | %DateTime{
             :calendar => atom(),
             :day => pos_integer(),
             :hour => non_neg_integer(),
             :microsecond => {non_neg_integer(), non_neg_integer()},
             :minute => non_neg_integer(),
             :month => pos_integer(),
             :second => non_neg_integer(),
             :std_offset => integer(),
             :time_zone => binary(),
             :utc_offset => integer(),
             :year => integer(),
             :zone_abbr => binary()
           },
       :description => nil | binary(),
       :external_id => nil | binary(),
       :id => nil | binary(),
       :identifier => nil | binary(),
       :internal_identifier => nil | binary(),
       :internal_url => nil | binary(),
       :labels => [binary()],
       :priority => nil | integer(),
       :source => :manual | nil | :tracker,
       :state => nil | binary(),
       :title => nil | binary(),
       :updated_at =>
         nil
         | %DateTime{
             :calendar => atom(),
             :day => pos_integer(),
             :hour => non_neg_integer(),
             :microsecond => {non_neg_integer(), non_neg_integer()},
             :minute => non_neg_integer(),
             :month => pos_integer(),
             :second => non_neg_integer(),
             :std_offset => integer(),
             :time_zone => binary(),
             :utc_offset => integer(),
             :year => integer(),
             :zone_abbr => binary()
           },
       :url => nil | binary()
     }
   ]}
."},
{"lib/symphony_elixir/orchestrator.ex", "Function persist_review_feedback_for_workspace/3 has no local return."},
{"lib/symphony_elixir/orchestrator.ex", "Unknown type: SymphonyElixir.Orchestrator.State.t/0."},
{"lib/symphony_elixir/orchestrator.ex", "The created anonymous function has no local return."},
{"lib/symphony_elixir/orchestrator.ex", "The function call fetch_issue will not succeed."},
{"lib/symphony_elixir/orchestrator.ex", "The function call update_issue_state will not succeed."},
{"lib/symphony_elixir/pr_watcher.ex", "Invalid type specification for function review_feedback."},
{"lib/symphony_elixir/pr_watcher.ex", "Function review_feedback/1 has no local return."},
{"lib/symphony_elixir/pr_watcher.ex", "Function review_feedback/2 has no local return."},
{"lib/symphony_elixir/pr_watcher.ex", "The function call status will not succeed."},
{"lib/symphony_elixir/pr_watcher.ex", "Function build_feedback_items/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function cached_feedback/3 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function review_item/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function comment_item/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function draft_reply/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function resolution_recommendation/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function contains_nit?/1 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function normalized_state/1 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function review_feedback_for_source/4 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function normalize_thread_states/1 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function normalize_cached_pr_url/2 will never be called."},
{"lib/symphony_elixir/pr_watcher.ex", "Function normalize_pr_url/1 will never be called."},
{"lib/symphony_elixir/repo_compatibility.ex", "The pattern can never match the type true."},
{"lib/symphony_elixir/run_policy.ex", "The function call update_issue_state will not succeed."},
{"lib/symphony_elixir/run_policy.ex", "The pattern variable _ can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/runner_runtime.ex", "The pattern pattern <__metadata@1, _current_link_target@1> can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/runner_runtime.ex", "The pattern variable __metadata@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/ui_proof.ex", "Unknown type: SymphonyElixir.UiProof.Result.t/0."},
{"lib/symphony_elixir_web/controllers/observability_api_controller.ex", "The pattern can never match the type {:error, :issue_not_found}."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_result_status/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "The created anonymous function has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function issue_payload_body/6 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function delivery_report_entry/3 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function delivery_explanation_payload/3 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function proof_summary/3 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function issue_id_from_entries/4 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function issue_detail_entry/4 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function restart_count/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function retry_attempt/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function running_entry_payload/2 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function retry_entry_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function paused_entry_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function skipped_entry_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function queue_entry_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function retry_issue_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function waiting_operator_summary_payload/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function paused_operator_summary_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function skipped_operator_summary_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function queue_operator_summary_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function review_thread_state_counts/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function review_follow_up_summary/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function workflow_profile_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function policy_pack_payload/0 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function runtime_health_payload/4 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function traceability_payload/5 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function review_thread_pr_url/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function proof_artifacts_payload/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function deploy_artifacts_payload/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function operator_summary_payload/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function pr_watcher_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_review_thread_states/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_review_thread_state_value/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function issue_operator_summary_payload/5 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function issue_runtime_health_payload/4 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function done_operator_summary/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function done_summary_from_history/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function tracked_issue_policy_class/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function run_state_policy_class/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Type mismatch in call without opaque term in member?."},
{"lib/symphony_elixir_web/presenter.ex", "Function queued_reason_summary/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function queued_next_step/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function skipped_reason_summary/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function recent_activity_payload/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function compatibility_report_from/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "The pattern can never match the type map()."},
{"lib/symphony_elixir_web/presenter.ex", "The pattern variable __result@1 can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir_web/presenter.ex", "Function delivery_pr_url_from_history/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function delivery_pr_url_from_summary/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_pr_url/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function decision_history_contains?/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_atom_string/1 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function tracked_issue_payload/1 has no local return."},
{"lib/symphony_elixir_web/presenter.ex", "The function call fetch_issue will not succeed."},
{"lib/symphony_elixir_web/presenter.ex", "Function normalize_tracked_issue_payload/1 will never be called."},
{"lib/symphony_elixir/agent_provider/claude.ex", "Unknown type: SymphonyElixir.AgentProvider.Claude.StreamState.t/0."},
{"lib/symphony_elixir/orchestrator.ex", "The pattern pattern <_issue@1, __refreshed_issue@1> can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/orchestrator.ex", :pattern_match_cov, {4554, 8}},
{"lib/symphony_elixir/workspace.ex", "The pattern pattern <__workspace@1, __issue_context@1, __lifecycle@1> can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir/workspace.ex", "The pattern pattern <__workspace@1, __lifecycle@1> can never match the type, because it is covered by previous clauses."},
{"lib/symphony_elixir_web/presenter.ex", "Function apply_persisted_review_state/2 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function persisted_check_list/3 will never be called."},
{"lib/symphony_elixir_web/presenter.ex", "Function latest_operator_signal/1 will never be called."},
]
